# Generated by Django 5.0.1 on 2024-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=10)),
                ("age", models.CharField(max_length=3)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
