# Generated by Django 5.0.1 on 2024-07-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_register_rename_phone_number_contact_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("batches", models.CharField(max_length=100)),
                ("fees", models.CharField(max_length=100)),
            ],
        ),
    ]
